tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "asdf"
brew "bat"
brew "exa"
brew "fd"
brew "fish"
brew "ghq"
brew "mas"
brew "ripgrep"
brew "tmux"
brew "trash"

cask "alacritty"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "kindle"
cask "notion"

mas "LINE", id: 539883307
mas "Yoink", id: 457622435
